### ISSUE TITLE
Better test coverage (meta issue)

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#250]
This meta issue can be closed if the following issues are resolved:

- [ ] #244 - Improve the test coverage of the grading module
- [ ] #245 - Automated end-to-end test of a fully configured system (integration test)
- [x] #246 - Automatically validate produced HTML
- [x] #247 - Automatically check for CSS syntax errors and problems
- [x] #248 - Automatically check for JS syntax errors and problems
- [ ] #249 - Robustness tests for the testrunner/solutions module

**Comment by martinmo** [comment]
Closing meta issue, will use milestones to organize this instead.
